Repository Acellera/htmd, pull requests merged in 2018-03, with the labels that each got.

#576 Uniformization of envvars and prerun in Lsf and Slurm
  htmd/parameterization/cli.py
  htmd/queues/lsfqueue.py
  htmd/queues/slurmqueue.py
Labels: enhancement

#577 Suspend appveyor
  README.md
  continuous-integration/appveyor/.appveyor.yml
  continuous-integration/appveyor/binstar-push.py
  continuous-integration/appveyor/move-conda-package.py
Labels: bug:low

#580 Introduces support for multiple queues/partitions in LsfQueue and Slu…
  htmd/queues/lsfqueue.py
  htmd/queues/slurmqueue.py
Labels: enhancement

#581 Small fixes on tests to pass on local deployments (acemanager install…
  htmd/parameterization/detect.py
  htmd/tests/run_inline_file_tests.py
Labels: bug:medium

#582 Toni fix ionize standard names
  htmd/builder/amber.py
  htmd/builder/charmm.py
  htmd/builder/ionize.py
  htmd/data/test-amber-build-nopp/3PTB/input.pdb
  htmd/data/test-amber-build-nopp/3PTB/leap.log
  htmd/data/test-amber-build-nopp/3PTB/log.txt
  htmd/data/test-amber-build-nopp/3PTB/structure.pdb
  htmd/data/test-amber-build-nopp/3PTB/structure.prmtop
  htmd/data/test-amber-build/3PTB/input.pdb
  htmd/data/test-amber-build/3PTB/leap.log
  htmd/data/test-amber-build/3PTB/log.txt
  htmd/data/test-amber-build/3PTB/structure.pdb
  htmd/data/test-amber-build/3PTB/structure.prmtop
  htmd/data/test-equilibration/3PTB/prerun/structure.pdb
  htmd/data/test-equilibration/3PTB/prerun/structure.prmtop
Labels: enhancement

#586 Fixed bug in MOL2 writing. Title should match the resname or tleap will complain
  htmd/molecule/writers.py
Labels: bug:medium

#591 Fix nglviewdeps
  htmd/model.py
  package/htmd-deps/DEPENDENCIES
  package/htmd-deps/write_meta_yaml.py
  sync_acellera_conda_channel_deps.py
Labels: bug:high

#596 fftype needs to be consistent. if it returns mol it ought to be a copy
  htmd/parameterization/fftype.py
Labels: enhancement

#599 bugfix for fftype. Masses are usually correct length but zeros
  htmd/data/test-param/benzamidine_cgenff/parameters/CGenFF_2b6/B3LYP-cc-pVDZ-vacuum/mol.psf
  htmd/parameterization/fftype.py
Labels: bug:medium

#604 Fix tutorials
  doc/source/userguide/advancedbuilding.rst
  doc/source/userguide/analysing.rst
  doc/source/userguide/introduction.rst
  tutorials/adaptive-sampling.ipynb
  tutorials/cxcl12-conformational-analysis.ipynb
  tutorials/getting-started-with-htmd.ipynb
  tutorials/htmd-molecules.ipynb
  tutorials/ligand-binding-analysis.ipynb
  tutorials/md-protocols.ipynb
  tutorials/projections.ipynb
  tutorials/protein-folding-analysis.ipynb
  tutorials/protein-preparation.ipynb
  tutorials/python-primer.ipynb
  tutorials/system-building-protein-in-membrane.ipynb
  tutorials/system-building-protein-ligand.ipynb
  tutorials/visualization.ipynb
Labels: bug:medium

#601 Fixes part of commit 0742ae4a329e352aa3e2688d08d6b56648fa2a39
  htmd/model.py
Labels: bug:low

#608 fixed guessAnglesDihedrals
  htmd/data/test-molecule-utils/NH4.pdb
  htmd/molecule/util.py
Labels: bug:medium

#614 Moves logging from htmd.ui into htmd.__init__
  htmd/__init__.py
  htmd/ui.py
Labels: bug:medium

#617 fixed some minor printing in parameterize
  htmd/parameterization/parameterset.py
  htmd/parameterization/readers.py
Labels: enhancement, parameterize
