Repository Acellera/htmd, pull requests merged in 2018-04, with the labels that each got.

#629 Fix condabuild
  htmd/data/HTMD_LICENCE.txt
  package/htmd-data/meta.yaml
Labels: bug:high, deployment

#636 Fix htmdlib
  htmd/lib/Linux/liblicense.so
  htmd/lib/Linux/libvmdparser.so
  htmd/lib/Linux/libxtc.so
  htmd/lib/Linux/mindist_ext.so
  htmd/lib/Linux/occupancy_ext.so
  htmd/lib/Linux/tmalign.so
  htmd/tests/run_inline_file_tests.py
Labels: bug:high

#637 abstract classes need ABCMeta
  htmd/adaptive/adaptive.py
  htmd/projections/projection.py
Labels: bug:medium

#640 bump htmd-data version
  package/htmd-data/meta.yaml
Labels: deployment

#646 Removing default fstep from readers
  htmd/molecule/readers.py
  htmd/projections/metric.py
Labels: enhancement

#655 Fix multiplequeues
  htmd/queues/lsfqueue.py
  htmd/queues/slurmqueue.py
Labels: bug:high

#657 change tutorial tests to only run tests starting in test_tutorial
  tutorials/test_tutorials.py
Labels: bug:high
