Repository Acellera/htmd, pull requests merged in 2018-12, with the labels that each got.

#832 Fixes conda-build
  package/htmd/build.sh
Labels: Priority: Critical, Type: Maintenance

#831 Make parameterize tests to work in a container
  htmd/charge/esp.py
  htmd/qm/test.py
Labels: Priority: Medium, Topic: Parameterize, Type: Enhancement

#833 Details which matter...
  htmd/parameterization/cli.py
Labels: Priority: Critical, Topic: Parameterize, Type: Bug
