Repository Acellera/htmd, pull requests merged in 2018-09, with the labels that each got.

#768 changing order in which resources is written due to a particular depl…
  htmd/queues/lsfqueue.py
Labels: Priority: High, Type: Maintenance

#777 Fix PRM writer for CGENFF
  htmd/parameterization/cli.py
  htmd/parameterization/writers.py
Labels: Priority: Critical, Type: Bug

#753 Improvements to custom QM calculators
  htmd/numbautil.py
  htmd/qm/custom.py
Labels: Priority: Medium, Type: Enhancement
