Repository Acellera/htmd, pull requests merged in 2018-06, with the labels that each got.

#711 Refactoring of Molecule file reading
  htmd/builder/amber.py
  htmd/molecule/molecule.py
  htmd/molecule/readers.py
  htmd/parameterization/writers.py
  htmd/smallmol/smallmol.py
Labels: Priority: Medium, Type: Enhancement

#716 Licensing and registration
  htmd/__init__.py
  htmd/lib/Linux/liblicense.so
  htmdx/cli.py
  htmdx/license.py
Labels: Priority: Critical, Type: Bug, Type: Maintenance

#714 Fixes one bug in ringpenetration and many errors in lgtm
  htmd/builder/charmm.py
  htmd/membranebuilder/ringpenetration.py
  htmd/metricdata.py
  htmd/model.py
  htmd/molecule/pdbx/reader/PdbxParser.py
  htmd/molecule/pdbx/reader/PdbxReader.py
  htmd/molecule/readers.py
  htmd/pathplanning.py
  htmd/smallmol/smallmol.py
  htmd/smallmol/tautomers.py
  htmd/util.py
  htmd/vmdgraphics.py
Labels: Priority: Medium, Type: Maintenance

#718 Fix AceCloudQueue
  htmd/queues/acecloudqueue.py
Labels: Priority: Critical, Type: Bug

#723 adds hack to circumvent XTCreader special case
  htmd/molecule/molecule.py
Labels: Priority: Critical, Type: Bug
