Repository Acellera/htmd, pull requests merged in 2018-11, with the labels that each got.

#796 Fixes ESP error behavior when passed Molecule without correct total charge
  doc/source-parameterize/tutorial.rst
  htmd/parameterization/cli.py
Labels: Priority: Critical, Topic: Parameterize, Type: Bug

#798 Remove inverse dihedral types in parameterize
  htmd/ffevaluation/ffevaluate.py
  htmd/parameterization/cli.py
  htmd/parameterization/dihedral.py
  htmd/parameterization/parameterset.py
  htmd/parameterization/writers.py
  htmd/qm/custom.py
  htmd/util.py
Labels: Priority: Critical, Topic: Parameterize, Type: Bug

#802 Parameterize: improve testing
  htmd/parameterization/test.py
Labels: Priority: Critical, Topic: Parameterize, Type: Enhancement

#805 Update voxeldescriptors.py
  htmd/molecule/voxeldescriptors.py
Labels: Priority: Medium, Type: Maintenance

#782 Refactor configuration and logging
  htmd/parameterization/cli.py
  htmd/parameterization/dihedral.py
  htmd/parameterization/parameterset.py
  htmd/parameterization/util.py
  htmd/qm/fake.py
  htmd/qm/psi4.py
Labels: Priority: Medium, Topic: Parameterize, Type: Enhancement

#817 fixed conda-build version to the one that works
  .travis.yml
Labels: Priority: Critical, Type: Maintenance

#823 Fixcondabuild
  .travis.yml
  package/htmd/meta.yaml
Labels: Priority: Critical, Type: Maintenance

#827 Hide irrelevant log messages
  htmd/charge/charge.py
  htmd/parameterization/cli.py
  htmd/parameterization/fftype.py
  htmd/parameterization/util.py
Labels: Priority: Medium, Topic: Parameterize, Type: Enhancement
