Repository Acellera/htmd, pull requests merged in 2018-08, with the labels that each got.

#751 fixes assignment through configapp yaml file to go through validation
  htmd/queues/lsfqueue.py
  htmd/queues/slurmqueue.py
Labels: Priority: High, Type: Bug, Type: Maintenance

#741 Membrane builder tutorial
  htmd/builder/charmm.py
  htmd/membranebuilder/build_membrane.py
  htmd/membranebuilder/dcdreporter.py
  htmd/membranebuilder/globalminimization.py
  htmd/membranebuilder/lipids/lipiddb.csv
  htmd/membranebuilder/ljfluid.py
  htmd/membranebuilder/simulate_openmm.py
  htmd/membranebuilder/wrappingdist.py
  tutorials/MembraneBuilder.ipynb
Labels: Type: Enhancement

#761 fix parsing of psi4.out file
  htmd/qm/psi4.py
Labels: Priority: High, Type: Bug

#765 improved ensurelist to support ranges
  htmd/util.py
Labels: Priority: Medium, Type: Enhancement
