Repository Acellera/htmd, pull requests merged in 2018-07, with the labels that each got.

#729 Parameter reading
  htmd/ffevaluation/ffevaluate.py
Labels: Type: Enhancement

#715 Parmed 3 fix
  htmd/ffevaluation/ffevaluate.py
  htmd/ffevaluation/test_ffevaluate.py
Labels: Priority: Medium, Type: Maintenance

#730 pin htmd-data version always
  package/htmd-deps/DEPENDENCIES
  package/htmd-deps/write_meta_yaml.py
Labels: Priority: Critical, Type: Maintenance

#735 pin joblib version
  htmd/parameterization/test.py
  htmd/qm/test.py
  package/htmd-deps/DEPENDENCIES
Labels: Priority: Critical, Type: Bug, Type: Maintenance

#732 New small implementation.
  htmd/smallmol/chemlab/periodictable.py
  htmd/smallmol/smallmol.py
Labels: Priority: Medium, Type: Enhancement

#740 FFEvaluate tutorial
  htmd/ffevaluation/ffevaluate.py
  htmd/ffevaluation/test_ffevaluate.py
  tutorials/FFEvaluate.ipynb
Labels: Type: Enhancement

#743 made the removed existing sentinel message debug level
  htmd/queues/simqueue.py
Labels: Priority: Medium, Type: Enhancement

#744 improves get and set docs
  htmd/molecule/molecule.py
Labels: Type: Enhancement

#541 Parameterize: new DFT functional and basis sets
  htmd/parameterization/cli.py
  htmd/qm/base.py
  htmd/qm/psi4.py
  htmd/qm/test.py
Labels: Topic: Parameterize, Type: Enhancement

#749 locking psi4 to a particular version, to avoid bad surprises
  package/htmd-deps/DEPENDENCIES
Labels: Priority: Critical, Type: Maintenance

#679 Parameterize: custom calculator
  htmd/parameterization/cli.py
  htmd/parameterization/dihedral.py
  htmd/qm/custom.py
Labels: Topic: Parameterize, Type: Enhancement

#742 MutualInformation fix
  htmd/mutualinformation.py
Labels: Priority: Medium, Type: Bug
