Repository Acellera/htmd, pull requests merged in 2019-09, with the labels that each got.

#912 Fix ACEMD tests for untrusted PRs
  htmd/protocols/equilibration_v2.py
  htmd/protocols/production_v6.py
Labels: Priority: Medium, Topic: ACEMD, Type: Bug

#910 Implement PlayQueue
  htmd/qm/base.py
  htmd/queues/playqueue.py
Labels: Priority: Medium, Type: Enhancement

#915 Enable QM property tests
  htmd/qm/test.py
Labels: Type: Maintenance

#911 Parameterize: integrate PlayQueue
  htmd/parameterization/cli.py
Labels: Priority: Medium, Topic: Parameterize, Type: Enhancement

#916 Parameterize: limit concurrent jobs
  htmd/parameterization/cli.py
  htmd/queues/playqueue.py
Labels: Priority: Medium, Topic: Parameterize, Type: Enhancement

#919 Fix #528
  htmd/qm/psi4.py
Labels: Topic: Parameterize, Type: Maintenance

#917 PlayQueue: set the parent of secondary jobs
  htmd/queues/playqueue.py
Labels: Priority: Medium, Topic: Parameterize, Type: Enhancement

#918 Parameterize: enable progress updates for QM jobs
  htmd/parameterization/cli.py
Labels: Priority: Medium, Topic: Parameterize, Type: Enhancement

#921 Fix PlayQueue.retrieve to handle killed jobs
  htmd/queues/playqueue.py
Labels: Priority: Medium, Topic: Parameterize, Type: Bug

#922 Update the progress messages
  htmd/parameterization/cli.py
Labels: Priority: Medium, Topic: Parameterize, Type: Enhancement

#924 Set default ncpus to 1. Rename ncpus to njobs to follow nomenclature
  htmd/__init__.py
  htmd/adaptive/adaptive.py
  htmd/config.py
  htmd/model.py
  htmd/mutualinformation.py
  htmd/projections/metric.py
  htmd/projections/tica.py
  htmd/simlist.py
  htmd/util.py
  htmd/versionwarnings.py
Labels: Priority: High, Type: Maintenance, Type: Support

#927 Parameterize: relax the check of Gasteiger charges
  htmd/parameterization/cli.py
Labels: Priority: Medium, Topic: Parameterize, Type: Enhancement

#928 Parameterize: fix PM progress for NNP
  htmd/parameterization/cli.py
Labels: Priority: Medium, Topic: Parameterize, Type: Bug
