Repository Acellera/htmd, pull requests merged in 2019-08, with the labels that each got.

#899 Added option to disable angle/dihedral regeneration
  htmd/builder/charmm.py
Labels: Priority: High

#892 Capture stderr messages in case of RDKit failures
  htmd/charge/charge.py
  htmd/parameterization/fixes.py
  htmd/parameterization/util.py
  htmd/util.py
Labels: Priority: High, Topic: Parameterize, Type: Enhancement

#903 Remove periodictable from deps
  htmd/parameterization/detect.py
  htmd/parameterization/readers.py
  htmd/parameterization/writers.py
  package/htmd-deps/DEPENDENCIES
  sync_acellera_conda_channel_deps.py
Labels: Priority: Medium, Type: Maintenance

#906 remove old and uneccesary deps. Clean up the syncing code
  package/htmd-deps/DEPENDENCIES
  sync_acellera_conda_channel_deps.py
Labels: Priority: Medium, Type: Maintenance

#904 remove acecloud from htmd
  htmd/parameterization/cli.py
  htmd/qm/psi4.py
  htmd/qm/test.py
  htmd/queues/acecloudqueue.py
  package/htmd-deps/DEPENDENCIES
Labels: Priority: Medium, Type: Maintenance

#905 removed requests library and updated registration code
  htmdx/cli.py
  package/htmd-deps/DEPENDENCIES
  package/htmd-deps/DEPENDENCIES_WIN
Labels: Priority: Medium, Type: Maintenance
